### ISSUE TITLE
complete this project

### ISSUE THREAD

**Issue by wbdsnx** [keijiro/BlazePoseBarracuda#1]
@keijiro I have been very happy since I saw this project, because finally some authors can apply the official model of mediapipe to unity. I am also studying these things. And I know little about the knowledge of shaders, which makes me confused all the time. I hope the author can complete this project as soon as possible! Thanks!

**Comment by keijiro** [comment]
Thanks a lot, but please understand that this issue tracker is dedicated for reporting technical issues.

I close this ticket as irrelevant.
