### ISSUE TITLE
the numbers of the detection points

### ISSUE THREAD

**Issue by cancaglar** [keijiro/BlazePoseBarracuda#2]
how can I increase the detection points? like I wanna get the position of left shoulder etc. but tehre is just 4 detection point

**Comment by keijiro** [comment]
Did you actually get the points? As far as I remember, this project is a failed attempt -- I couldn't run the model on Barracuda.

**Comment by cancaglar** [comment]
well I thought I get the point because there is 4 points that following the body but its just a straight vertical line :/ I guess it looked like this because it wasn't working like you said.
